### ISSUE TITLE
"Value out of bounds" when using Decimal/Numeric with TVP parameter

### ISSUE THREAD

**Issue by jbrunken** [pekim/tedious#232]
Using 1.8.1, I'm getting the following exception when trying to pass any number as a Decimal or Numeric column in a TVP parameter:
```
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:705:11)
    at Buffer.writeUInt8 (buffer.js:715:5)
    at WritableTrackingBuffer.writeUInt8 (/src/node_modules/tedious/lib/tracking-buffer/writable-tracking-buffer.js:77:17)
    at Object.TYPE.writeTypeInfo (/src/node_modules/tedious/lib/data-type.js:253:14)
    at Object.TYPE.writeParameterData (/src/node_modules/tedious/lib/data-type.js:1093:21)
    at new RpcRequestPayload (/src/node_modules/tedious/lib/rpcrequest-payload.js:66:22)
    at Connection.callProcedure (/src/node_modules/tedious/lib/connection.js:982:56)
```
Is this a known issue?   Thanks

**Comment by patriksimek** [comment]
I believe this is caused by missing `precision` value in column definition.

```
columns: [
    {name: 'number', type: TYPES.Numeric, precision: 18, scale: 0},
]
```

**Comment by jbrunken** [comment]
That's it.  Thanks!
