### ISSUE TITLE
npm install fails with 1.10.0

### ISSUE THREAD

**Issue by lee-houghton** [pekim/tedious#249]
Hi,

I've had problems on both Linux and Windows with the 1.10.0 version of tedious on NPM. I have to go into the `node_modules/tedious` directory myself and run `npm install`, or use the git master version. Presumably this is because the build script isn't getting run. Is this a known issue?

```
$ npm install tedious
$ node -e "require('tedious')"

module.js:340
    throw err;
          ^
Error: Cannot find module 'tedious'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:8
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at startup (node.js:80:7)
    at node.js:906:3
$ npm install tedious@1.9.0
tedious@1.9.0 node_modules/tedious
├── sprintf@0.1.1
├── big-number@0.3.0
└── iconv-lite@0.4.2
$ node -e "require('tedious')"
$
```

**Comment by patriksimek** [comment]
Can't reproduce the issue in neither of my environments.

**Comment by lee-houghton** [comment]
Maybe it's the installed version of node or npm. I'll see if I can narrow
it down.

**Comment by arthurschreiber** [comment]
What's your node / iojs version?

**Comment by lee-houghton** [comment]
After a little more testing, it works for me with Node 0.12 on Windows and fails with Node 0.10.36 on Linux. In both cases I created a new directory and ran `npm init` then `npm i --save tedious`.

**Comment by arthurschreiber** [comment]
Does something look off if you check the lib folder on the systems where this is not working? Files missing or anything like that?

**Comment by lee-houghton** [comment]
Yeah, the lib folder in tedious isn't even there on the affected machines! I looked in the package file that npm downloaded and the lib file was missing there too. 

If I run `npm install` in the `node_modules/tedious` directory, it then works as expected and can be `require`d.

So I checked the npm registry and the file that's on there _does_ include the lib folder, which led me to think that npm is caching the bad version somehow. After running `rm  /home/lhoughton/.npm/tedious/1.10.0/package.tgz` on the affected machine I was then able to `npm install` and `require` tedious with no problems... 

Is it possible a bad version of tedious 1.10.0 was uploaded and then replaced with a fixed version, and my co-workers and I just happen to be unlucky enough to have cached the bad version?

**Comment by patriksimek** [comment]
I don't think it is possible because npm doesn't allow to publish same version twice.

**Comment by lee-houghton** [comment]
Yeah, you're correct (I should have remembered that). In that case, I don't know how it happened. Could it be an npm bug? If you want to close this, I'm happy enough that I have a workaround.

**Comment by SyRenity** [comment]
Happened to me as well, first time it occurs on any module that I've used.

**Comment by arthurschreiber** [comment]
Closing this due to inactivity. Feel free to open a new issue if you continue to encounter this problem.

**Comment by wayne-o** [comment]
I am getting this now: 

NPM 5.0.3
Node v8.1.3

```Loaded configuration file "config/config.json".
Using environment "development".
{ Error: Cannot find module 'tedious'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize/lib/dialects/mssql/query.js:10:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize/lib/dialects/mssql/index.js:6:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at new Sequelize (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize/lib/sequelize.js:212:19)
    at getSequelizeInstance (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/lib/tasks/db.js:385:12)
    at getMigrator (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/lib/tasks/db.js:394:21)
    at Object.task (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/lib/tasks/db.js:24:14)
    at /home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:17:23
    at tryCatcher (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:569:18) code: 'MODULE_NOT_FOUND' }
'db:migrate' errored after 28 ms
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize/lib/dialects/mssql/query.js:10:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize/lib/dialects/mssql/index.js:6:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at new Sequelize (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize/lib/sequelize.js:212:19)
    at getSequelizeInstance (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/lib/tasks/db.js:385:12)
    at getMigrator (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/lib/tasks/db.js:394:21)
    at Object.task (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/lib/tasks/db.js:24:14)
    at /home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:17:23
    at tryCatcher (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/vagrant/.nvm/versions/node/v8.1.3/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:569:18)```

**Comment by wayne-o** [comment]
It works on Node v6.11.1
