### ISSUE TITLE
v1.12.* breaks on Azure Mobile Services

### ISSUE THREAD

**Issue by jtmilne** [pekim/tedious#296]
Azure Mobile Services is pinned to Node v0.8.28. 

With the latest release of Tedious it now crashes on all connections with the following exception: 

```
An unhandled exception occurred. TypeError: Object #<Socket> has no method 'unpipe' 
at MessageIO.encryptAllFutureTraffic (D:\home\site\wwwroot\App_Data\config\scripts\node_modules\pwc-common\node_modules\mssql\node_modules\tedious\lib\message-io.js:179:17) 
at SecurePair.MessageIO.startTls (D:\home\site\wwwroot\App_Data\config\scripts\node_modules\pwc-common\node_modules\mssql\node_modules\tedious\lib\message-io.js:167:22) 
at SecurePair.EventEmitter.emit (events.js:93:17) at SecurePair.maybeInitFinished (tls.js:933:10) 
at CleartextStream.CryptoStream._push (tls.js:514:15) at SecurePair.cycle (tls.js:901:20) 
at EncryptedStream.CryptoStream.write (tls.js:285:13) at MessageIO.tlsHandshakeData (D:\home\site\wwwroot\App_Data\config\scripts\node_modules\pwc-common\node_modules\mssql\node_modules\tedious\lib\message-io.js:188:38) 
at Connection.STATE.SENT_TLSSSLNEGOTIATION.events.data (D:\home\site\wwwroot\App_Data\config\scripts\node_modules\pwc-common\node_modules\mssql\node_modules\tedious\lib\connection.js:184:33) 
at Connection.dispatchEvent (D:\home\site\wwwroot\App_Data\config\scripts\node_modules\pwc-common\node_modules\mssql\node_modules\tedious\lib\connection.js:781:59)```

**Comment by arthurschreiber** [comment]
We dropped official node 0.8 support a while ago. Tedious continued to work with 0.8 by accident as we did not yet make any use of newer node APIs. That changed with tedious 1.12.

Node 0.8 has not received any patches for a long time. Does anyone else feel strongly about 0.8 support?

**Comment by bretcope** [comment]
Supporting 0.8 seems like it would really hold back Tedious, especially when it comes to the stream changes.

**Comment by jtmilne** [comment]
My understanding is that Azure Mobile Services will be migrating off 0.8 in the not too distant future so that should solve my issue without having to provide legacy support in Tedious. I will close this request.
