### ISSUE TITLE
Cannot assign to read only property 'tdsVersion' of #<Object>

### ISSUE THREAD

**Issue by dachev** [pekim/tedious#356]
I am experiencing sporadic and unpredictable crashes caused by the following exception:

```
Application has thrown an uncaught exception and is terminated:
TypeError: Cannot assign to read only property 'tdsVersion' of #<Object>
    at Parser.<anonymous> (c:\PATH\TO\CODE\node_modules\seriate\node_modules\mssql\node_modules\tedious\lib\connection.js:288:42)
    at Parser.emit (events.js:107:17)
    at Parser.<anonymous> (c:\PATH\TO\CODE\node_modules\seriate\node_modules\mssql\node_modules\tedious\lib\token\token-stream-parser.js:51:15)
    at Parser.emit (events.js:107:17)
    at readableAddChunk (c:\PATH\TO\CODE\node_modules\seriate\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:199:16)
    at Parser.Readable.push (c:\PATH\TO\CODE\node_modules\seriate\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:163:10)
    at Parser.Transform.push (c:\PATH\TO\CODE\node_modules\seriate\node_modules\mssql\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:133:32)
    at doneParsing (c:\PATH\TO\CODE\node_modules\seriate\node_modules\mssql\node_modules\tedious\lib\token\stream-parser.js:82:17)
    at c:\PATH\TO\CODE\node_modules\seriate\node_modules\mssql\node_modules\tedious\lib\token\loginack-token-parser.js:22:19
    at c:\PATH\TO\CODE\node_modules\seriate\node_modules\mssql\node_modules\tedious\lib\token\stream-parser.js:142:9

```

Tedious version: 1.13.1
Node version: 0.12
OS: Windows

**Comment by arthurschreiber** [comment]
Tedious currently modifies the `config` object that you pass to the `Connection` constructor. The exception here is complaining that it can't set the `tdsVersion` property. How does your `config` object look like?

**Comment by dachev** [comment]
@arthurschreiber We use https://github.com/lorenwest/node-config. It looks like this module might be creating immutable config objects. Thanks for your help. I think it's save to close this ticket.

**Comment by WeihanLi** [comment]
I've met the sample problem, I use the `config` package to manage my db config,

my db config json:
``` json
{
    "connectionStrings": {
      "default": {
        "user": "",
        "password": "",
        "server": "",
        "database": "",
        "connectionTimeout": 10000,
        "requestTimeout": 60000,
        "retryTimes": 3,
        "options": {
          "encrypt": true
        },
        "pool": {
            "max": 1024,
            "min": 1,
            "idleTimeoutMillis": 30000
        }
      }
    }
  }
```


the error are as follows:
``` 
UnhandledPromiseRejectionWarning: TypeError: Cannot assign to read only property 'options' of object '#<Object>'
warning.js:18
    at new ConnectionPool (c:\projects\zhongyi\crawler\CommunityCrawler\fangdi\node_modules\mssql\lib\base.js:142:25)
    at new ConnectionPool (c:\projects\zhongyi\crawler\CommunityCrawler\fangdi\node_modules\mssql\lib\tedious.js:193:1)
    at Object.connect (c:\projects\zhongyi\crawler\CommunityCrawler\fangdi\node_modules\mssql\lib\base.js:1623:22)
```

**Comment by arthurschreiber** [comment]
I guess you're running on an older version of `tedious`? Newer versions (I think 3.x and later) don't modify the passed in config anymore.

**Comment by WeihanLi** [comment]
I'm using the latest `mssql` with 4.2.2 which has dependency with `tedious` above 2.7.1, should I add `tedious` with 3.x version?
