### ISSUE TITLE
Unknown type: 164

### ISSUE THREAD

**Issue by mhingston** [pekim/tedious#375]
Hi, I'm getting `Unknown type: 164` when calling a sproc that uses a cursor. Tedious 1.13.2, SQL Server 2008, default connection options.

	CREATE PROCEDURE [dbo].[UnknownType164Test]
	AS

	DECLARE BatchCursor CURSOR FOR
	SELECT TOP 10 ID
	FROM MyTable

	DECLARE @ID int
	OPEN BatchCursor
	FETCH NEXT FROM BatchCursor
	WHILE @@FETCH_STATUS = 0
	BEGIN
		FETCH NEXT FROM BatchCursor
		INTO @ID
		SELECT @ID
	END
	CLOSE BatchCursor
	DEALLOCATE BatchCursor

Stack Trace:

    Error: Unknown type: 164
        at Parser.parseTokens (/Users/Me/Test/node_modules/tedious/lib/token/stream-parser.js:94:30)
        at Parser._transform (/Users/Me/Test/node_modules/tedious/lib/token/stream-parser.js:67:14)
        at Parser.Transform._read (/Users/Me/Test/node_modules/readable-stream/lib/_stream_transform.js:159:10)
        at Parser.Transform._write (/Users/Me/Test/node_modules/readable-stream/lib/_stream_transform.js:147:83)
        at doWrite (/Users/Me/Test/node_modules/readable-stream/lib/_stream_writable.js:313:64)
        at writeOrBuffer (/Users/Me/Test/node_modules/readable-stream/lib/_stream_writable.js:302:5)
        at Parser.Writable.write (/Users/Me/Test/node_modules/readable-stream/lib/_stream_writable.js:241:11)
        at Parser.addBuffer (/Users/Me/Test/node_modules/tedious/lib/token/token-stream-parser.js:59:26)
        at Connection.sendDataToTokenStreamParser (/Users/Me/Test/node_modules/tedious/lib/connection.js:684:37)
        at Connection.data (/Users/Me/Test/node_modules/tedious/lib/connection.js:1210:21)
        at Connection.dispatchEvent (/Users/Me/Test/node_modules/tedious/lib/connection.js:559:45)
        at MessageIO.<anonymous> (/Users/Me/Test/node_modules/tedious/lib/connection.js:476:16)
        at emitOne (events.js:90:13)
        at MessageIO.emit (events.js:182:7)
        at ReadablePacketStream.<anonymous> (/Users/Me/Test/node_modules/tedious/lib/message-io.js:101:13)
        at emitOne (events.js:90:13)

**Comment by mhingston** [comment]
I resolved the issue by changing to:

	CREATE PROCEDURE [dbo].[UnknownType164Test]
	AS

	DECLARE BatchCursor CURSOR FOR
	SELECT TOP 10 ID
	FROM MyTable

	DECLARE @ID int
	OPEN BatchCursor
	FETCH NEXT FROM BatchCursor
    INTO @ID
	WHILE @@FETCH_STATUS = 0
	BEGIN
	    SELECT @ID
	    FETCH NEXT FROM BatchCursor
	    INTO @ID
	END
	CLOSE BatchCursor
	DEALLOCATE BatchCursor

**Comment by 57r31** [comment]
yep just run into same problem, seems tedious still dont support FETCH NEXT FROM BatchCursor
without INTO
