### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by PeterNierop** [pekim/tedious#390]
On one of my customers I have this odd behavior.
Most of the day the Node app communicates just fine with the SQL server. But sometimes I get this

events.js:154
      throw er; // Unhandled 'error' event
      ^
 ConnectionError: Failed to connect to 172.16.252.11:1433 in 15000ms
    at ConnectionError (C:\ExosMobile\node_modules\tedious\lib\errors.js:12:12)
    at Connection.connectTimeout (C:\ExosMobile\node_modules\tedious\lib\connect
ion.js:467:28)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

Testing to my limited knowledge seems that if I make the 'ping' time to run a stored procedure shorter, from original once a minute to every 3 seconds then this problem almost disappears. But still once so often it seems to fail.

I do use the connection pool.

So I like to ask two questions. What is the best way to do the error handling if at all possible. 
And is there a way to configure this particular connection time to survive?

Thank you very much. 

Btw, I am rather happy with the Tedious library. Allows me to write fast apps. 12k calls per second in burst mode.

**Comment by PeterNierop** [comment]
Bump

**Comment by TheFarmer1** [comment]
When I see this problem, the application crashes.  Is that normal?

**Comment by PeterNierop** [comment]
Sadly yes, indeed the app crashes. I keep it alive by using Respawn to start and restart my app. It does crash about once every week. 
Best regards,
Peter Nierop 

    On Wednesday, November 30, 2016 4:28 AM, TheFarmer1 <notifications@github.com> wrote:
 

 When I see this problem, the application crashes. Is that normal?—

**Comment by tvrprasad** [comment]
@PeterNierop @TheFarmer1  Any chance you may be able to put together a repro? I tried this with small connectTimeout values to force timeout but couldn't repro.
