### ISSUE TITLE
Unsupported dataLength 18 for IntN

### ISSUE THREAD

**Issue by mhingston** [pekim/tedious#398]
Hi,

Just got the following uncaught exception (SQL Server 2008/TDS 7.4/Tedious 1.14.0):

    MyProject\node_modules\tedious\lib\token\stream-parser.js:121

            callback();
            ^
    Error: Unsupported dataLength 18 for IntN
        at MyProject\node_modules\tedious\lib\value-parser.js:125:43
        at MyProject\node_modules\tedious\lib\token\stream-parser.js:147:9
        at Parser.awaitData (MyProject\node_modules\tedious\lib\token\stream-parser.js:121:9)
        at Parser.readUInt8 (MyProject\node_modules\tedious\lib\token\stream-parser.js:144:12)
        at readDataLength (MyProject\node_modules\tedious\lib\value-parser.js:64:27)
        at MyProject\node_modules\tedious\lib\value-parser.js:90:5
        at readTextPointerNull (MyProject\node_modules\tedious\lib\value-parser.js:36:5)
        at valueParse (MyProject\node_modules\tedious\lib\value-parser.js:89:3)
        at next (MyProject\node_modules\tedious\lib\token\row-token-parser.js:19:5)
        at MyProject\node_modules\tedious\lib\token\row-token-parser.js:35:7
        at MyProject\node_modules\tedious\lib\value-parser.js:402:7
        at MyProject\node_modules\tedious\lib\token\stream-parser.js:410:9
        at Parser.awaitData (MyProject\node_modules\tedious\lib\token\stream-parser.js:121:9)
        at Parser.readBuffer (MyProject\node_modules\tedious\lib\token\stream-parser.js:407:12)
        at readNChars (MyProject\node_modules\tedious\lib\value-parser.js:401:19)
        at MyProject\node_modules\tedious\lib\value-parser.js:202:20
        at MyProject\node_modules\tedious\lib\token\stream-parser.js:180:9
        at Parser.awaitData (MyProject\node_modules\tedious\lib\token\stream-parser.js:121:9)
        at Parser.readUInt16LE (MyProject\node_modules\tedious\lib\token\stream-parser.js:177:12)
        at readDataLength (MyProject\node_modules\tedious\lib\value-parser.js:67:27)
        at MyProject\node_modules\tedious\lib\value-parser.js:90:5
        at readTextPointerNull (MyProject\node_modules\tedious\lib\value-parser.js:36:5)

I'm not able to replicate this at present, but it appears to have happened just calling execSql with a simple select statement.

**Comment by mhingston** [comment]
This is still happening occasionally.

Most recent stack trace:

`MyProject\node_modules\tedious\lib\token\stream-parser.js:121

        callback();
        ^
Error: Unsupported dataLength 10 for IntN
    at MyProject\node_modules\tedious\lib\value-parser.js:125:43
    at MyProject\node_modules\tedious\lib\token\stream-parser.js:147:9
    at Parser.awaitData (MyProject\node_modules\tedious\lib\token\stream-parser.js:121:9)
    at Parser.readUInt8 (MyProject\node_modules\tedious\lib\token\stream-parser.js:144:12)
    at readDataLength (MyProject\node_modules\tedious\lib\value-parser.js:64:27)
    at MyProject\node_modules\tedious\lib\value-parser.js:90:5
    at readTextPointerNull (MyProject\node_modules\tedious\lib\value-parser.js:36:5)
    at valueParse (MyProject\node_modules\tedious\lib\value-parser.js:89:3)
    at next (MyProject\node_modules\tedious\lib\token\row-token-parser.js:19:5)
    at MyProject\node_modules\tedious\lib\token\row-token-parser.js:35:7
    at MyProject\node_modules\tedious\lib\value-parser.js:402:7
    at MyProject\node_modules\tedious\lib\token\stream-parser.js:410:9
    at Parser.awaitData (MyProject\node_modules\tedious\lib\token\stream-parser.js:121:9)
    at Parser.readBuffer (MyProject\node_modules\tedious\lib\token\stream-parser.js:407:12)
    at readNChars (MyProject\node_modules\tedious\lib\value-parser.js:401:19)
    at MyProject\node_modules\tedious\lib\value-parser.js:202:20
    at MyProject\node_modules\tedious\lib\token\stream-parser.js:180:9
    at Parser.awaitData (MyProject\node_modules\tedious\lib\token\stream-parser.js:121:9)
    at Parser.readUInt16LE (MyProject\node_modules\tedious\lib\token\stream-parser.js:177:12)
    at readDataLength (MyProject\node_modules\tedious\lib\value-parser.js:67:27)
    at MyProject\node_modules\tedious\lib\value-parser.js:90:5
    at readTextPointerNull (MyProject\node_modules\tedious\lib\value-parser.js:36:5)`

This happened when I called `execSQL` with a parameterised statement to invoke a stored procedure which takes a single `Int` argument. The actual call looks like this: `exec MyDatabase.dbo.GetSelection 20`. The stored procedure looks like this:

`USE [MyDatabase]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[GetSelection]
    @FilterID int
AS

SET NOCOUNT OFF

SELECT MAX(Account.AccountName) [Name], MAX(Account.AccountID) [AccountID], MAX(Account.AccountName) [AccountName]
FROM MyOtherDatabase.dbo.FilterFranchise
JOIN MyOtherDatabase.dbo.Franchise ON Franchise.FranchiseID = FilterFranchise.FranchiseID
JOIN MyOtherDatabase.dbo.Site ON Site.SiteID = Franchise.SiteID
JOIN Account ON Account.AccountID = Site.AccountID
WHERE FilterFranchise.FilterID = @FilterID
GROUP BY Account.AccountID

SELECT MAX(Account.AccountName + ' > ' + Site.SiteName) [Name], MAX(Account.AccountID) [AccountID], MAX(Account.AccountName) [AccountName]
FROM MyOtherDatabase.dbo.FilterFranchise
JOIN MyOtherDatabase.dbo.Franchise ON Franchise.FranchiseID = FilterFranchise.FranchiseID
JOIN MyOtherDatabase.dbo.Site ON Site.SiteID = Franchise.SiteID
JOIN dbo.Account ON Account.AccountID = Site.AccountID
WHERE FilterFranchise.FilterID = @FilterID
GROUP BY Site.SiteID

SELECT MAX(Account.AccountName + ' > ' + Site.SiteName + ' > ' + Franchise.FranchiseName) [Name], MAX(Account.AccountID) [AccountID], MAX(Account.AccountName) [AccountName]
FROM MyOtherDatabase.dbo.FilterFranchise
JOIN MyOtherDatabase.dbo.Franchise ON Franchise.FranchiseID = FilterFranchise.FranchiseID
JOIN MyOtherDatabase.dbo.Site ON Site.SiteID = Franchise.SiteID
JOIN Account ON Account.AccountID = Site.AccountID
WHERE FilterFranchise.FilterID = @FilterID
GROUP BY Franchise.FranchiseID`

**Comment by IanChokS** [comment]
Hi @mhingston, are you still experiencing this issue with the latest tedious version?
